In [1]:
#NHL website
import pandas as pd

In [2]:
url = 'https://www.nhl.com/flyers/roster/2019'

In [53]:
tables = pd.read_html(url)
tables

[                                               Player  \
                                                     #
 0                                  A.  Andy  Andreoff
 1                             N.  Nicolas  Aube-Kubel
 2                                C.  Connor  Bunnaman
 3                                 S.  Sean  Couturier
 4                                   J.  Joel  Farabee
 5                                M.  Morgan  Frost  *
 6                             C.  Claude  Giroux  (C)
 7                                    D.  Derek  Grant
 8                                    K.  Kevin  Hayes
 9                                     D.  David  Kase
 10                                T.  Travis  Konecny
 11                                S.  Scott  Laughton
 12                                O.  Oskar  Lindblom
 13                                  S.  Samuel  Morin
 14                                 T.  Tyler  Pitlick
 15                                 M.  Michael  Raffl
 16                                G.  German  Rubtsov
 17                                 C.  Chris  Stewart
 18                                 N.  Nate  Thompson
 19                              C.  Carsen  Twarynski
 20                            J.  James  van Riemsdyk
 21                                 J.  Jakub  Voracek
 22                              M.  Mikhail  Vorobyev
 23                                                 10
 24                                                 62
 25                                                 82
 26                                                 14
 27                                                 86
 28                                                 48
 29                                                 28
 30                                                 38
 31                                                 13
 32                                                 72
 33                                                 11
 34                                                 21
 35                                                 23
 36                                                 55
 37                                                 17
 38                                                 17
 39                                                 50
 40                                                 44
 41                                                 11
 42                                                 81
 43                                                 25
 44                                                 93
 45                                                 24
 46  Player  A.  Andy  Andreoff  N.  Nicolas  Aube-...

                                    Unnamed: 1_level_0 Unnamed: 2_level_0  \
                                                   Pos                 Sh
 0                                                 NaN                NaN
 1                                                 NaN                NaN
 2                                                 NaN                NaN
 3                                                 NaN                NaN
 4                                                 NaN                NaN
 5                                                 NaN                NaN
 6                                                 NaN                NaN
 7                                                 NaN                NaN
 8                                                 NaN                NaN
 9                                                 NaN                NaN
 10                                                NaN                NaN
 11                                                NaN                NaN
 12                                                NaN                NaN
 13                                                NaN                NaN
 14                                                NaN                NaN
 15                                                NaN                NaN
 16                                                NaN                NaN
 17                                                NaN                NaN
 18                                                NaN                NaN
 19                                                NaN                NaN
 20                                                NaN                NaN
 21                                                NaN                NaN
 22                                                NaN                NaN
 23                                                  C                  L
 24                                                 RW                  R
 25                                                  C                  L
 26                                                  C                  L
 27                                                 LW                  L
 28                                                  C                  L
 29                                                  C                  R
 30                                                  C                  L
 31                                                  C                  L
 32                                                 RW                  L
 33                                                 RW                  R
 34                                                  C                  L
 35                                                 LW                  L
 36                                                 LW                  L
 37                                                  C                  R
 38                                                 LW                  L
 39                                                  C                  L
 40                                                 RW                  R
 41                                                  C                  L
 42                                                 LW                  L
 43                                                 LW                  L
 44                                                 RW                  L
 45                                                  C                  L
 46  #  Pos  Sh  Ht  Wt  Born  Birthplace  10  C  L...                NaN

    Unnamed: 3_level_0 Unnamed: 4_level_0    Unnamed: 5_level_0  \
                    Ht                 Wt                  Born
 0                 NaN                NaN                   NaN
 1                 NaN                NaN                   NaN
 2                 NaN                NaN                   NaN
 3                 NaN                NaN                   NaN
 4                 NaN                NaN                   NaN
 5                 NaN                NaN                   NaN
 6                 NaN                NaN                   NaN
 7                 NaN                NaN                   NaN
 8                 NaN                NaN                   NaN
 9                 NaN                NaN                   NaN
 10                NaN                NaN                   NaN
 11                NaN                NaN                   NaN
 12                NaN                NaN                   NaN
 13                NaN                NaN                   NaN
 14                NaN                NaN                   NaN
 15                NaN                NaN                   NaN
 16                NaN                NaN                   NaN
 17                NaN                NaN                   NaN
 18                NaN                NaN                   NaN
 19                NaN                NaN                   NaN
 20                NaN                NaN                   NaN
 21                NaN                NaN                   NaN
 22                NaN                NaN                   NaN
 23          6'1"6' 1"              203.0  05/17/91May 17, 1991
 24        5'11"5' 11"              187.0  05/10/96May 10, 1996
 25          6'1"6' 1"              207.0  04/16/98Apr 16, 1998
 26          6'3"6' 3"              211.0   12/07/92Dec 7, 1992
 27          6'0"6' 0"              164.0  02/25/00Feb 25, 2000
 28        5'11"5' 11"              170.0  05/14/99May 14, 1999
 29        5'11"5' 11"              185.0  01/12/88Jan 12, 1988
 30          6'3"6' 3"              206.0  04/20/90Apr 20, 1990
 31          6'5"6' 5"              216.0   05/08/92May 8, 1992
 32        5'11"5' 11"              169.0  01/28/97Jan 28, 1997
 33        5'10"5' 10"              175.0  03/11/97Mar 11, 1997
 34          6'1"6' 1"              190.0  05/30/94May 30, 1994
 35          6'1"6' 1"              191.0  08/15/96Aug 15, 1996
 36          6'6"6' 6"              202.0  07/12/95Jul 12, 1995
 37          6'2"6' 2"              200.0   11/01/91Nov 1, 1991
 38          6'0"6' 0"              200.0   12/01/88Dec 1, 1988
 39          6'2"6' 2"              178.0  06/27/98Jun 27, 1998
 40          6'2"6' 2"              242.0  10/30/87Oct 30, 1987
 41          6'1"6' 1"              205.0   10/05/84Oct 5, 1984
 42          6'2"6' 2"              198.0  11/24/97Nov 24, 1997
 43          6'3"6' 3"              217.0   05/04/89May 4, 1989
 44          6'2"6' 2"              214.0  08/15/89Aug 15, 1989
 45          6'2"6' 2"              194.0   01/05/97Jan 5, 1997
 46                NaN                NaN                   NaN

        Unnamed: 6_level_0
                Birthplace
 0                     NaN
 1                     NaN
 2                     NaN
 3                     NaN
 4                     NaN
 5                     NaN
 6                     NaN
 7                     NaN
 8                     NaN
 9                     NaN
 10                    NaN
 11                    NaN
 12                    NaN
 13                    NaN
 14                    NaN
 15                    NaN
 16                    NaN
 17                    NaN
 18                    NaN
 19                    NaN
 20                    NaN
 21                    NaN
 22                    NaN
 23     Pickering, ON, CAN
 24    Slave Lake, AB, CAN
 25        Guelph, ON, CAN
 26       Phoenix, AZ, USA
 27      Syracuse, NY, USA
 28        Aurora, ON, CAN
 29        Hearst, ON, CAN
 30    Abbotsford, BC, CAN
 31    Dorchester, MA, USA
 32             Kadan, CZE
 33        London, ON, CAN
 34      Oakville, ON, CAN
 35             Gävle, SWE
 36  Lac-Beauport, QC, CAN
 37   Minneapolis, MN, USA
 38           Villach, AUT
 39           Chekhov, RUS
 40       Toronto, ON, CAN
 41     Anchorage, AK, USA
 42    St. Albert, AB, CAN
 43    Middletown, NJ, USA
 44            Kladno, CZE
 45               Ufa, RUS
 46                    NaN  ,
                      Player
 0        A.  Andy  Andreoff
 1   N.  Nicolas  Aube-Kubel
 2      C.  Connor  Bunnaman
 3       S.  Sean  Couturier
 4         J.  Joel  Farabee
 5      M.  Morgan  Frost  *
 6   C.  Claude  Giroux  (C)
 7          D.  Derek  Grant
 8          K.  Kevin  Hayes
 9           D.  David  Kase
 10      T.  Travis  Konecny
 11      S.  Scott  Laughton
 12      O.  Oskar  Lindblom
 13        S.  Samuel  Morin
 14       T.  Tyler  Pitlick
 15       M.  Michael  Raffl
 16      G.  German  Rubtsov
 17       C.  Chris  Stewart
 18       N.  Nate  Thompson
 19    C.  Carsen  Twarynski
 20  J.  James  van Riemsdyk
 21       J.  Jakub  Voracek
 22    M.  Mikhail  Vorobyev,
      # Pos Sh           Ht   Wt                  Born             Birthplace
 0   10   C  L    6'1"6' 1"  203  05/17/91May 17, 1991     Pickering, ON, CAN
 1   62  RW  R  5'11"5' 11"  187  05/10/96May 10, 1996    Slave Lake, AB, CAN
 2   82   C  L    6'1"6' 1"  207  04/16/98Apr 16, 1998        Guelph, ON, CAN
 3   14   C  L    6'3"6' 3"  211   12/07/92Dec 7, 1992       Phoenix, AZ, USA
 4   86  LW  L    6'0"6' 0"  164  02/25/00Feb 25, 2000      Syracuse, NY, USA
 5   48   C  L  5'11"5' 11"  170  05/14/99May 14, 1999        Aurora, ON, CAN
 6   28   C  R  5'11"5' 11"  185  01/12/88Jan 12, 1988        Hearst, ON, CAN
 7   38   C  L    6'3"6' 3"  206  04/20/90Apr 20, 1990    Abbotsford, BC, CAN
 8   13   C  L    6'5"6' 5"  216   05/08/92May 8, 1992    Dorchester, MA, USA
 9   72  RW  L  5'11"5' 11"  169  01/28/97Jan 28, 1997             Kadan, CZE
 10  11  RW  R  5'10"5' 10"  175  03/11/97Mar 11, 1997        London, ON, CAN
 11  21   C  L    6'1"6' 1"  190  05/30/94May 30, 1994      Oakville, ON, CAN
 12  23  LW  L    6'1"6' 1"  191  08/15/96Aug 15, 1996             Gävle, SWE
 13  55  LW  L    6'6"6' 6"  202  07/12/95Jul 12, 1995  Lac-Beauport, QC, CAN
 14  17   C  R    6'2"6' 2"  200   11/01/91Nov 1, 1991   Minneapolis, MN, USA
 15  17  LW  L    6'0"6' 0"  200   12/01/88Dec 1, 1988           Villach, AUT
 16  50   C  L    6'2"6' 2"  178  06/27/98Jun 27, 1998           Chekhov, RUS
 17  44  RW  R    6'2"6' 2"  242  10/30/87Oct 30, 1987       Toronto, ON, CAN
 18  11   C  L    6'1"6' 1"  205   10/05/84Oct 5, 1984     Anchorage, AK, USA
 19  81  LW  L    6'2"6' 2"  198  11/24/97Nov 24, 1997    St. Albert, AB, CAN
 20  25  LW  L    6'3"6' 3"  217   05/04/89May 4, 1989    Middletown, NJ, USA
 21  93  RW  L    6'2"6' 2"  214  08/15/89Aug 15, 1989            Kladno, CZE
 22  24   C  L    6'2"6' 2"  194   01/05/97Jan 5, 1997               Ufa, RUS,
                                                Player  \
                                                     #
 0                                   J.  Justin  Braun
 1                                  M.  Mark  Friedman
 2                            S.  Shayne  Gostisbehere
 3                                    R.  Robert  Hagg
 4                                 P.  Philippe  Myers
 5                                  M.  Matt  Niskanen
 6                                  I.  Ivan  Provorov
 7                                 T.  Travis  Sanheim
 8                                                  61
 9                                                  52
 10                                                 53
 11                                                  8
 12                                                  5
 13                                                 15
 14                                                  9
 15                                                  6
 16  Player  J.  Justin  Braun  M.  Mark  Friedman ...

                                    Unnamed: 1_level_0 Unnamed: 2_level_0  \
                                                   Pos                 Sh
 0                                                 NaN                NaN
 1                                                 NaN                NaN
 2                                                 NaN                NaN
 3                                                 NaN                NaN
 4                                                 NaN                NaN
 5                                                 NaN                NaN
 6                                                 NaN                NaN
 7                                                 NaN                NaN
 8                                                   D                  R
 9                                                   D                  R
 10                                                  D                  L
 11                                                  D                  L
 12                                                  D                  R
 13                                                  D                  R
 14                                                  D                  L
 15                                                  D                  L
 16  #  Pos  Sh  Ht  Wt  Born  Birthplace  61  D  R...                NaN

    Unnamed: 3_level_0 Unnamed: 4_level_0    Unnamed: 5_level_0  \
                    Ht                 Wt                  Born
 0                 NaN                NaN                   NaN
 1                 NaN                NaN                   NaN
 2                 NaN                NaN                   NaN
 3                 NaN                NaN                   NaN
 4                 NaN                NaN                   NaN
 5                 NaN                NaN                   NaN
 6                 NaN                NaN                   NaN
 7                 NaN                NaN                   NaN
 8           6'2"6' 2"              205.0  02/10/87Feb 10, 1987
 9         5'11"5' 11"              185.0  12/25/95Dec 25, 1995
 10        5'11"5' 11"              180.0  04/20/93Apr 20, 1993
 11          6'2"6' 2"              204.0   02/08/95Feb 8, 1995
 12          6'5"6' 5"              210.0  01/25/97Jan 25, 1997
 13          6'1"6' 1"              203.0   12/06/86Dec 6, 1986
 14          6'1"6' 1"              201.0  01/13/97Jan 13, 1997
 15          6'3"6' 3"              181.0  03/29/96Mar 29, 1996
 16                NaN                NaN                   NaN

          Unnamed: 6_level_0
                  Birthplace
 0                       NaN
 1                       NaN
 2                       NaN
 3                       NaN
 4                       NaN
 5                       NaN
 6                       NaN
 7                       NaN
 8      Minneapolis, MN, USA
 9          Toronto, ON, CAN
 10  Pembroke Pines, FL, USA
 11             Uppsala, SWE
 12         Moncton, NB, CAN
 13        Virginia, MN, USA
 14           Yaroslavl, RUS
 15         Elkhorn, MB, CAN
 16                      NaN  ,
                      Player
 0         J.  Justin  Braun
 1        M.  Mark  Friedman
 2  S.  Shayne  Gostisbehere
 3          R.  Robert  Hagg
 4       P.  Philippe  Myers
 5        M.  Matt  Niskanen
 6        I.  Ivan  Provorov
 7       T.  Travis  Sanheim,
     # Pos Sh           Ht   Wt                  Born               Birthplace
 0  61   D  R    6'2"6' 2"  205  02/10/87Feb 10, 1987     Minneapolis, MN, USA
 1  52   D  R  5'11"5' 11"  185  12/25/95Dec 25, 1995         Toronto, ON, CAN
 2  53   D  L  5'11"5' 11"  180  04/20/93Apr 20, 1993  Pembroke Pines, FL, USA
 3   8   D  L    6'2"6' 2"  204   02/08/95Feb 8, 1995             Uppsala, SWE
 4   5   D  R    6'5"6' 5"  210  01/25/97Jan 25, 1997         Moncton, NB, CAN
 5  15   D  R    6'1"6' 1"  203   12/06/86Dec 6, 1986        Virginia, MN, USA
 6   9   D  L    6'1"6' 1"  201  01/13/97Jan 13, 1997           Yaroslavl, RUS
 7   6   D  L    6'3"6' 3"  181  03/29/96Mar 29, 1996         Elkhorn, MB, CAN,
                                               Player  \
                                                    #
 0                                 B.  Brian  Elliott
 1                                   C.  Carter  Hart
 2                                     A.  Alex  Lyon
 3                                                 37
 4                                                 79
 5                                                 34
 6  Player  B.  Brian  Elliott  C.  Carter  Hart  ...

                                   Unnamed: 1_level_0 Unnamed: 2_level_0  \
                                                  Pos                 Sh
 0                                                NaN                NaN
 1                                                NaN                NaN
 2                                                NaN                NaN
 3                                                  G                 --
 4                                                  G                 --
 5                                                  G                 --
 6  #  Pos  Sh  Ht  Wt  Born  Birthplace  37  G  -...                NaN

   Unnamed: 3_level_0 Unnamed: 4_level_0    Unnamed: 5_level_0  \
                   Ht                 Wt                  Born
 0                NaN                NaN                   NaN
 1                NaN                NaN                   NaN

In [54]:
type(tables)

list

In [58]:
df = df = tables[0]
df.head(15)

,Player,Unnamed: 1_level_0,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0
,#,Pos,Sh,Ht,Wt,Born,Birthplace
0,A. Andy Andreoff,NaN,NaN,NaN,NaN,NaN,NaN
1,N. Nicolas Aube-Kubel,NaN,NaN,NaN,NaN,NaN,NaN
2,C. Connor Bunnaman,NaN,NaN,NaN,NaN,NaN,NaN
3,S. Sean Couturier,NaN,NaN,NaN,NaN,NaN,NaN
4,J. Joel Farabee,NaN,NaN,NaN,NaN,NaN,NaN
5,M. Morgan Frost *,NaN,NaN,NaN,NaN,NaN,NaN
6,C. Claude Giroux (C),NaN,NaN,NaN,NaN,NaN,NaN
7,D. Derek Grant,NaN,NaN,NaN,NaN,NaN,NaN
8,K. Kevin Hayes,NaN,NaN,NaN,NaN,NaN,NaN
9,D. David Kase,NaN,NaN,NaN,NaN,NaN,NaN
10,T. Travis Konecny,NaN,NaN,NaN,NaN,NaN,NaN
11,S. Scott Laughton,NaN,NaN,NaN,NaN,NaN,NaN
12,O. Oskar Lindblom,NaN,NaN,NaN,NaN,NaN,NaN
13,S. Samuel Morin,NaN,NaN,NaN,NaN,NaN,NaN
14,T. Tyler Pitlick,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
df[8:]

,Player,Unnamed: 1_level_0,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0
,#,Pos,Sh,Ht,Wt,Born,Birthplace
8,K. Kevin Hayes,NaN,NaN,NaN,NaN,NaN,NaN
9,D. David Kase,NaN,NaN,NaN,NaN,NaN,NaN
10,T. Travis Konecny,NaN,NaN,NaN,NaN,NaN,NaN
11,S. Scott Laughton,NaN,NaN,NaN,NaN,NaN,NaN
12,O. Oskar Lindblom,NaN,NaN,NaN,NaN,NaN,NaN
13,S. Samuel Morin,NaN,NaN,NaN,NaN,NaN,NaN
14,T. Tyler Pitlick,NaN,NaN,NaN,NaN,NaN,NaN
15,M. Michael Raffl,NaN,NaN,NaN,NaN,NaN,NaN
16,G. German Rubtsov,NaN,NaN,NaN,NaN,NaN,NaN
17,C. Chris Stewart,NaN,NaN,NaN,NaN,NaN,NaN
18,N. Nate Thompson,NaN,NaN,NaN,NaN,NaN,NaN
19,C. Carsen Twarynski,NaN,NaN,NaN,NaN,NaN,NaN
20,J. James van Riemsdyk,NaN,NaN,NaN,NaN,NaN,NaN
21,J. Jakub Voracek,NaN,NaN,NaN,NaN,NaN,NaN
22,M. Mikhail Vorobyev,NaN,NaN,NaN,NaN,NaN,NaN
23,10,C,L,"6'1""6' 1""",203.0,"05/17/91May 17, 1991","Pickering, ON, CAN"
24,62,RW,R,"5'11""5' 11""",187.0,"05/10/96May 10, 1996","Slave Lake, AB, CAN"
25,82,C,L,"6'1""6' 1""",207.0,"04/16/98Apr 16, 1998","Guelph, ON, CAN"
26,14,C,L,"6'3""6' 3""",211.0,"12/07/92Dec 7, 1992","Phoenix, AZ, USA"
27,86,LW,L,"6'0""6' 0""",164.0,"02/25/00Feb 25, 2000","Syracuse, NY, USA"
28,48,C,L,"5'11""5' 11""",170.0,"05/14/99May 14, 1999","Aurora, ON, CAN"
29,28,C,R,"5'11""5' 11""",185.0,"01/12/88Jan 12, 1988","Hearst, ON, CAN"
30,38,C,L,"6'3""6' 3""",206.0,"04/20/90Apr 20, 1990","Abbotsford, BC, CAN"
31,13,C,L,"6'5""6' 5""",216.0,"05/08/92May 8, 1992","Dorchester, MA, USA"
32,72,RW,L,"5'11""5' 11""",169.0,"01/28/97Jan 28, 1997","Kadan, CZE"
33,11,RW,R,"5'10""5' 10""",175.0,"03/11/97Mar 11, 1997","London, ON, CAN"
34,21,C,L,"6'1""6' 1""",190.0,"05/30/94May 30, 1994","Oakville, ON, CAN"
35,23,LW,L,"6'1""6' 1""",191.0,"08/15/96Aug 15, 1996","Gävle, SWE"
36,55,LW,L,"6'6""6' 6""",202.0,"07/12/95Jul 12, 1995","Lac-Beauport, QC, CAN"
37,17,C,R,"6'2""6' 2""",200.0,"11/01/91Nov 1, 1991","Minneapolis, MN, USA"
38,17,LW,L,"6'0""6' 0""",200.0,"12/01/88Dec 1, 1988","Villach, AUT"
39,50,C,L,"6'2""6' 2""",178.0,"06/27/98Jun 27, 1998","Chekhov, RUS"
40,44,RW,R,"6'2""6' 2""",242.0,"10/30/87Oct 30, 1987","Toronto, ON, CAN"
41,11,C,L,"6'1""6' 1""",205.0,"10/05/84Oct 5, 1984","Anchorage, AK, USA"
42,81,LW,L,"6'2""6' 2""",198.0,"11/24/97Nov 24, 1997","St. Albert, AB, CAN"
43,25,LW,L,"6'3""6' 3""",217.0,"05/04/89May 4, 1989","Middletown, NJ, USA"
44,93,RW,L,"6'2""6' 2""",214.0,"08/15/89Aug 15, 1989","Kladno, CZE"
45,24,C,L,"6'2""6' 2""",194.0,"01/05/97Jan 5, 1997","Ufa, RUS"
46,Player A. Andy Andreoff N. Nicolas Aube-...,# Pos Sh Ht Wt Born Birthplace 10 C L...,NaN,NaN,NaN,NaN,NaN

In [57]:
df.dtypes

Player              #              object
Unnamed: 1_level_0  Pos            object
Unnamed: 2_level_0  Sh             object
Unnamed: 3_level_0  Ht             object
Unnamed: 4_level_0  Wt            float64
Unnamed: 5_level_0  Born           object
Unnamed: 6_level_0  Birthplace     object
dtype: object

In [11]:
df_1 = df_1 = tables[4]
df_1.head(15)

                     Player
0         J.  Justin  Braun
1        M.  Mark  Friedman
2  S.  Shayne  Gostisbehere
3          R.  Robert  Hagg
4       P.  Philippe  Myers
5        M.  Matt  Niskanen
6        I.  Ivan  Provorov
7       T.  Travis  Sanheim

In [61]:
# Dependencies
from bs4 import BeautifulSoup
import requests
import pymongo

In [62]:
# Initialize PyMongo to work with MongoDBs
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

In [63]:
# Define database and collection
db = client.flyers_db
collection = db.articles

In [64]:
# URL of page to be scraped
url = 'https://www.nhl.com/flyers/roster/2019'

# Retrieve page with the requests module
response = requests.get(url)
# Create BeautifulSoup object; parse with 'html.parser'
soup = BeautifulSoup(response.text, 'html.parser')

In [69]:
results__ = soup.find_all('table', class_='split-table')
results__

[<table class="split-table">
 <tr class="split-table-tr">
 <td class="split-table-td pinned">
 <div class="split-table-col split-table-col__pinned">
 <table class="data-table data-table__forwards data-table__pinned">
 <thead>
 <tr>
 <th class="name-col">
                                                                     Player
                                                             </th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td class="name-col">
 <a href="/player/andy-andreoff-8476404">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8476404.jpg">
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">A.</span>
 <span class="name-col__item name-col__firstName">Andy</span>
 <span class="name-col__item name-col__lastName">Andreoff</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </img></a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/nicolas-aube-kubel-8477979">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8477979.jpg">
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">N.</span>
 <span class="name-col__item name-col__firstName">Nicolas</span>
 <span class="name-col__item name-col__lastName">Aube-Kubel</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </img></a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/connor-bunnaman-8479382">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8479382.jpg">
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">C.</span>
 <span class="name-col__item name-col__firstName">Connor</span>
 <span class="name-col__item name-col__lastName">Bunnaman</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </img></a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/sean-couturier-8476461">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8476461.jpg">
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">S.</span>
 <span class="name-col__item name-col__firstName">Sean</span>
 <span class="name-col__item name-col__lastName">Couturier</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </img></a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/joel-farabee-8480797">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8480797.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">J.</span>
 <span class="name-col__item name-col__firstName">Joel</span>
 <span class="name-col__item name-col__lastName">Farabee</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/morgan-frost-8480028">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8480028.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">M.</span>
 <span class="name-col__item name-col__firstName">Morgan</span>
 <span class="name-col__item name-col__lastName">Frost</span>
 <span class="name-col__item name-col__special">

                                                                                     *
                                                                             </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/claude-giroux-8473512">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8473512.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">C.</span>
 <span class="name-col__item name-col__firstName">Claude</span>
 <span class="name-col__item name-col__lastName">Giroux</span>
 <span class="name-col__item name-col__special">
                                                                                     (C)
                                                                             </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/derek-grant-8474683">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8474683.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">D.</span>
 <span class="name-col__item name-col__firstName">Derek</span>
 <span class="name-col__item name-col__lastName">Grant</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/kevin-hayes-8475763">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8475763.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">K.</span>
 <span class="name-col__item name-col__firstName">Kevin</span>
 <span class="name-col__item name-col__lastName">Hayes</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/david-kase-8478436">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8478436.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">D.</span>
 <span class="name-col__item name-col__firstName">David</span>
 <span class="name-col__item name-col__lastName">Kase</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/travis-konecny-8478439">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8478439.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">T.</span>
 <span class="name-col__item name-col__firstName">Travis</span>
 <span class="name-col__item name-col__lastName">Konecny</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/scott-laughton-8476872">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8476872.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">S.</span>
 <span class="name-col__item name-col__firstName">Scott</span>
 <span class="name-col__item name-col__lastName">Laughton</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/oskar-lindblom-8478067">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8478067.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">O.</span>
 <span class="name-col__item name-col__firstName">Oskar</span>
 <span class="name-col__item name-col__lastName">Lindblom</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/samuel-morin-8477502">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8477502.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">S.</span>
 <span class="name-col__item name-col__firstName">Samuel</span>
 <span class="name-col__item name-col__lastName">Morin</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/tyler-pitlick-8475752">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8475752.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">T.</span>
 <span class="name-col__item name-col__firstName">Tyler</span>
 <span class="name-col__item name-col__lastName">Pitlick</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/michael-raffl-8477290">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8477290.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">M.</span>
 <span class="name-col__item name-col__firstName">Michael</span>
 <span class="name-col__item name-col__lastName">Raffl</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/german-rubtsov-8479424">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8479424.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">G.</span>
 <span class="name-col__item name-col__firstName">German</span>
 <span class="name-col__item name-col__lastName">Rubtsov</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/chris-stewart-8473485">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8473485.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">C.</span>
 <span class="name-col__item name-col__firstName">Chris</span>
 <span class="name-col__item name-col__lastName">Stewart</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/nate-thompson-8470775">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8470775.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">N.</span>
 <span class="name-col__item name-col__firstName">Nate</span>
 <span class="name-col__item name-col__lastName">Thompson</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/carsen-twarynski-8479358">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8479358.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">C.</span>
 <span class="name-col__item name-col__firstName">Carsen</span>
 <span class="name-col__item name-col__lastName">Twarynski</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/james-van-riemsdyk-8474037">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8474037.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">J.</span>
 <span class="name-col__item name-col__firstName">James</span>
 <span class="name-col__item name-col__lastName">van Riemsdyk</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/jakub-voracek-8474161">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8474161.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">J.</span>
 <span class="name-col__item name-col__firstName">Jakub</span>
 <span class="name-col__item name-col__lastName">Voracek</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 <tr>
 <td class="name-col">
 <a href="/player/mikhail-vorobyev-8478844">
 <img class="player-photo" onerror="this.src = 'https://cms.nhl.bamgrid.com/images/headshots/current/60x60/skater.jpg'" src="https://cms.nhl.bamgrid.com/images/headshots/current/60x60/8478844.jpg"/>
 <div class="name-col__list">
 <span class="name-col__item name-col__firstInitial">M.</span>
 <span class="name-col__item name-col__firstName">Mikhail</span>
 <span class="name-col__item name-col__lastName">Vorobyev</span>
 <span class="name-col__item name-col__special">
 </span>
 </div>
 </a>
 </td>
 </tr>
 </tbody>
 </table>
 </div>
 </td>
 <td class="split-table-td scrollable">
 <div class="split-table-col split-table-col__scrollable">
 <table class="data-table data-table__forwards data-table__scrollable">
 <thead>
 <tr>
 <th class="number-col">#</th>
 <th class="position-col">Pos</th>
 <th class="shoots-col">Sh</th>
 <th class="height-col">Ht</th>
 <th class="weight-col">Wt</th>
 <th class="birthdate-col">Born</th>
 <th class="hometown-col">Birthplace</th>
 </tr>
 </thead>
 <tbody>
 <tr>
 <td class="number-col fixed-width-font">10</td>
 <td class="position-col fixed-width-font">C</td>
 <td class="shoots-col fixed-width-font">L</td>
 <td class="height-col fixed-width-font"><span class="xs-sm-md-only">6'1"</span><span class="all-but-xs-sm-md">6' 1"</span></td>
 <td class="weight-col fixed-width-font">203</td>
 <td class="birthdate-col"><span class="xs-sm-md-only">05/17/91</span><span class="all-but-xs-sm-md">May 17, 1991</span></td>
 <td class="hometown-col">Pickering, ON, CAN</td>
 </tr>
 <tr>
 <td class="number-col fixed-width-font">62</td>
 <td class="position-col fixed-width-font">RW</td>
 <td class="shoots-col fixed-width-font">R</td>
 <td class="height-col fixed-width-font"><span class="xs-sm-md-only">5'11"</span><span class="all-but-xs-sm-md">5' 11"</span></td>
 <td class="weight-col fixed-width-font">187</td>
 <td class="birthdate-col"><span class="xs-sm-md-only">05/10/96</span><span class="all-but-xs-sm-md">May 10, 1996</span></td>
 <td class="hometown-col">Slave Lake, AB, CAN</td>
 </tr>
 <tr>
 <td class="number-col fixed-width-font">82</td>
 <td class="position-col fixed-width-font">C</td>
 <td class="shoots-col fixed-width-font">L</td>
 <td class="height-col fixed-width-font"><span class="xs-sm-md-only">6'1"</span><span class="all-but-xs-sm-md">6' 1"</span></td>
 <td class="weight-col fixed-width-font">207</td>
 <td class="birthdate-col"><span class="xs-sm-md-only">04/16/98</span><span class="all-but-xs-sm-md">Apr 16, 1998</span></td>
 <td class="hometown-col">Guelph, ON, CAN</td>
 </tr>
 <tr>
 <td class="number-col fixed-width-font">14</td>
 <td class="position-col fixed-width-font">C</td>
 <td class="shoots-col fixed-width-font">L</td>
 <td class="height-col fixed-width-font"><span class="xs-sm-md-only">6'3"</span><span class="all-but-xs-sm-md">6' 3"</span></td>
 <td class="weight-col fixed-width-font">211</td>
 <td class="birthdate-col"><span class="xs-sm-md-only">12/07/92</span><span class="all-but-xs-sm-md">Dec 7, 1992</span></td>
 <td class="hometown-col">Phoenix, AZ, USA</td>
 </tr>
 <tr>
 <td class="number-col fixed-width-font">86</td>
 <td class="position-col fixed-width-font">LW</td>
 <td class="shoots-col fixed-width-font">L</td>
 <td class="height-col fixed-width-font"><span class="xs-sm-md-only">6'0"</span><span class="all-but-xs-sm-md">6' 0"</span></td>
 <td class="weight-col fixed-width-font">164</td>
 <td class="birthdate-col"><span class="xs-sm-md-only">02/25/00</span><span class="all-but-xs-sm-md">Feb 25, 2000</span></td>
 <td class="hometown-col">Syracuse, NY, USA</td>
 </tr>
 <tr>
 <td class="number-col fixed-width-font">48</td>
 <td class="position-col fixed-width-font">C</td>
 <td class="shoots-col fixed-width-font">L</td>
 <td class="height-col fixed-width-font"><span class="xs-sm-md-only">5'11"</span><span class="all-but-xs-sm-md">5' 11"</span></td>
 <td class="weight-col fixed-width-font">170</td>
 <td class="birthdate-col"><span class="xs-sm-md-only">05/14/99</span><span class="all-but-xs-sm-md">May 14, 1999</span></td>
 <td class="hometown-col">Aurora, ON, CAN</td>
 </tr>
 <tr>
 <td class="number-col fixed-width-font">28</td>
 <td class="position-col fixed-width-font">C</td>
 <td class="shoots-col fixed-width-font">R</td>
 <td class="height-col fixed-width-font"><span class="xs-sm-md-only">5'11"</span><span class="all-but-xs-sm-md">5' 11"</span></td>
 <td class="weight-col fixed-width-font">185</td>
 <td class="birthdate-col"><span class="xs-sm-md-only">01/12/88</span><span class="all-but-xs-sm-md">Jan 12, 1988</span></td>
 <td class="hometown-col">Hearst, ON, CAN</td>
 </tr>
 <tr>
 <td class="number-col fixed-width-font">38</td>
 <td class="position-col fixed-width-font">C</td>
 <td class="shoots-col fixed-width-font">L</td>
 <td class="height-col fixed-width-font"><span class="xs-sm-md-only">6'3"</span><span class="all-but-xs-sm-md">6' 3"</span></td>
 <td class="weight-col fixed-width-font">206</td>
 <td class="birthdate-col"><span class="xs-sm-md-only">04/20/90</span><span class="all-but-xs-sm-md">Apr 20, 1990</span></td>
 <td class="hometown-col">Abbotsford, BC, CAN</td>
 </tr>
 <tr>
 <td class="number-col fixed-width-font">13</td>
 <td class="position-col fixed-width-font">C</td>
 <td class="shoots-col fixed-width-font">L</td>
 <td class="height-col fixed-width-font"><span class="xs-sm-md-only">6'5"</span><span class="all-but-xs-sm-md">6' 5"</span></td>
 <td class="weight-col fixed-width-font">216</td>
 <td class="birthdate-col"><span class="xs-sm-md-only">05/08/92</span><span class="all-but-xs-sm-md">May 8, 1992</span></td>
 <td class="hometown-col">Dorchester, MA, USA</td>
 </tr>
 <tr>
 <td class="number-col fixed-width-font">72</td>
 <td class="position-col fixed-width-font">RW</td>
 <td class="shoots-col fixed-width-font">L</td>
 <td class="height-col fixed-width-font"><span class="xs-sm-md-only">5'11"</span><span class="all-but-xs-sm-md">5' 11"</span></td>
 <td class="weight-col fixed-width-font">169</td>
 <td class="birthdate-col"><span class="xs-sm-md-only">01/28/97</span><span class="all-but-xs-sm-md">Jan 28, 1997</span></td>
 <td class="hometown-col">Kadan, CZE</td>
 </tr>
 <tr>
 <td class="number-col fixed-width-font">11</td>
 <td class="position-col fixed-width-font">RW</td>
 <td class="shoots-col fixed-width-font">R</td>
 <td class="height-col fixed-width-font"><span class="xs-sm-md-only">5'10"</span><span class="all-but-xs-sm-md">5' 10"</span></td>

In [99]:
# Retrieve the parent divs for all articles
results = soup.find_all('div', class_='name-col__list')
results
player_firstname = []
player_lastname = []
team = []
for result in results:
    first_name = result.find('span', class_='name-col__item name-col__firstName').text
    last_name = result.find('span', class_='name-col__item name-col__lastName').text
    
    print("-----")
    print(first_name)
    print(last_name)
    
    player_firstname.append(first_name)
    player_lastname.append(last_name)

-----
Andy
Andreoff
-----
Nicolas
Aube-Kubel
-----
Connor
Bunnaman
-----
Sean
Couturier
-----
Joel
Farabee
-----
Morgan
Frost
-----
Claude
Giroux
-----
Derek
Grant
-----
Kevin
Hayes
-----
David
Kase
-----
Travis
Konecny
-----
Scott
Laughton
-----
Oskar
Lindblom
-----
Samuel
Morin
-----
Tyler
Pitlick
-----
Michael
Raffl
-----
German
Rubtsov
-----
Chris
Stewart
-----
Nate
Thompson
-----
Carsen
Twarynski
-----
James
van Riemsdyk
-----
Jakub
Voracek
-----
Mikhail
Vorobyev
-----
Justin
Braun
-----
Mark
Friedman
-----
Shayne
Gostisbehere
-----
Robert
Hagg
-----
Philippe
Myers
-----
Matt
Niskanen
-----
Ivan
Provorov
-----
Travis
Sanheim
-----
Brian
Elliott
-----
Carter
Hart
-----
Alex
Lyon

In [83]:
type(player_lastname)

list

In [100]:
df5 = pd.DataFrame(player_firstname,player_lastname)

In [103]:
df6 = df5.reset_index()
df6

           index         0
0       Andreoff      Andy
1     Aube-Kubel   Nicolas
2       Bunnaman    Connor
3      Couturier      Sean
4        Farabee      Joel
5          Frost    Morgan
6         Giroux    Claude
7          Grant     Derek
8          Hayes     Kevin
9           Kase     David
10       Konecny    Travis
11      Laughton     Scott
12      Lindblom     Oskar
13         Morin    Samuel
14       Pitlick     Tyler
15         Raffl   Michael
16       Rubtsov    German
17       Stewart     Chris
18      Thompson      Nate
19     Twarynski    Carsen
20  van Riemsdyk     James
21       Voracek     Jakub
22      Vorobyev   Mikhail
23         Braun    Justin
24      Friedman      Mark
25  Gostisbehere    Shayne
26          Hagg    Robert
27         Myers  Philippe
28      Niskanen      Matt
29      Provorov      Ivan
30       Sanheim    Travis
31       Elliott     Brian
32          Hart    Carter
33          Lyon      Alex

In [104]:
df8 = df6[['0', 'index']]

KeyError: "['0'] not in index"